codealongs/cat-collector/catcollector/catcollector/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
]

codealongs/cat-collector/catcollector/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about,name='about'),
    path('cats/', views.cats_index, name='index'),
    path('cats/<int:cat_id>/', views.cats_detail, name='detail'),
    path('cats/create/', views.CatCreate.as_view(), name='cats_create'),
    path('cats/<int:pk>/update/', views.CatUpdate.as_view(), name='cats_update'),
    path('cats/<int:pk>/delete/', views.CatDelete.as_view(), name='cats_delete'),
    path('cats/<int:cat_id>/add_feeding/', views.add_feeding, name='add_feeding'),
]

kargarookollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('' , views.home , name='home' ),
    path('about' , views.about , name='about'),
    path('roo-list', views.roo_list, name='hoppys'),
    path('roo-details/<int:roo_id>', views.roo_detail, name='detail'),
    path('roo/chip' , views.RooChipped.as_view() , name='chip'),
    path('roo/<int:pk>/update/' , views.RooUpdate.as_view() , name='roo_update'),
    path('roo/<int:pk>/delete/' , views.RooDelete.as_view() , name='roo_delete'),
    path('ride/<int:roo_id>/create' , views.ride_create , name='ride_create'),
    path('roo-riding-species' , views.species , name='species'),
    path('roo-riding-species/create' , views.species_create , name='species_create'),
]

codealongs/cat-collector/catcollector/main_app/models.py
from django.db import models
from django.urls import reverse

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

# Create your models here.
class Cat(models.Model):
    name = models.CharField(max_length = 100)
    breed = models.CharField(max_length = 100)
    description = models.TextField(max_length = 250)
    age = models.IntegerField()

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'cat_id': self.id})



class Feeding(models.Model):
    date = models.DateField('feeding date')
    meal = models.CharField(
        max_length=1,
        # add the 'choices' field option
        choices=MEALS,
        # set the default value for meal to be 'B'
        default=MEALS[0][0]
    )
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/models.py
from django.db import models
from django.urls import reverse



# Create your models here.

class Species(models.Model):
    name = models.CharField(max_length = 100)
    def __str__(self):
        return self.name

class Roo(models.Model):
    name = models.CharField(max_length=100)
    height = models.CharField(max_length=100)
    age = models.IntegerField()
    description = models.TextField(max_length=250)
    favorite_species_to_kick = models.CharField(max_length=100)
    ridden_by = models.ManyToManyField(Species) # Please ignore this line. Many to many is actually accomplished through the Ride's model. Many Roo's to Many Species through Rides.
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'roo_id': self.id})


def species_list():
    specList = []
    for s in Species.objects.all():
        specList.append((s.id , s.name))
    # print(species_list)
    if not species_list:
        specList.append( ('Fail' , 'Upload some species first in New Rider Species!'))

    return specList

class Ride(models.Model):
    roo = models.ForeignKey(Roo, on_delete=models.CASCADE)
    species = models.ForeignKey(Species, on_delete=models.CASCADE , choices=species_list())
    duration = models.IntegerField()
    notes = models.TextField(max_length = 500)

    class Meta:
        ordering = ['-duration']

    def __str__(self):
        return f"Ride involing {self.species} riding the Roo named {self.roo}."

main_app/forms.py
from django.forms import ModelForm
from .models import Ride, Species

class RidingForm(ModelForm):
  class Meta:
    model = Ride
    fields = ['duration' , 'species' , 'notes']


class SpeciesForm(ModelForm):
  class Meta:
    model = Species
    fields = '__all__'

codealongs/cat-collector/catcollector/main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Cat
# Add the following import
from django.http import HttpResponse
from .models import Cat
from .forms import FeedingForm

# Add the Cat class & list and view function below the imports
""" class Cat:  # Note that parens are optional if not inheriting from another class
  def __init__(self, name, breed, description, age):
    self.name = name
    self.breed = breed
    self.description = description
    self.age = age

cats = [
  Cat('Lolo', 'tabby', 'foul little demon', 3),
  Cat('Sachi', 'tortoise shell', 'diluted tortoise shell', 0),
  Cat('Raven', 'black tripod', '3 legged cat', 4)
] """

class CatCreate(CreateView):
  model = Cat
  fields = '__all__'
  # or fields = ['name', 'breed', 'description', 'age']
  # success_url = '/cats/'

class CatUpdate(UpdateView):
  model = Cat
  # Let's disallow the renaming of a cat by excluding the name field!
  fields = ['breed', 'description', 'age']

class CatDelete(DeleteView):
  model = Cat
  success_url = '/cats/'

# Define the home view
def home(request):
  return render(request,'base.html')

def about(request):
  return render(request, 'about.html')

  # Add new view
def cats_index(request):
  cats = Cat.objects.all()
  return render(request, 'cats/index.html', { 'cats': cats })

def cats_detail(request, cat_id):
  cat = Cat.objects.get(id=cat_id)
  # instantiate FeedingForm to be rendered in the template
  feeding_form = FeedingForm()
  return render(request, 'cats/detail.html', {
    # include the cat and feeding_form in the context
    'cat': cat, 'feeding_form': feeding_form
  })

def add_feeding(request, cat_id):
    # create a ModelForm instance using the data in request.POST
  form = FeedingForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_feeding = form.save(commit=False)
    new_feeding.cat_id = cat_id
    new_feeding.save()

  return redirect('detail', cat_id=cat_id)

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Roo, Species, Ride
from .forms import RidingForm, SpeciesForm


# Create your views here.
def home(request):
    return redirect('about')

def about(request):
    return render(request,'about.html')

def roo_list(request):
    kangas = Roo.objects.all()
    return render(request , 'roo_central/hoppy_bois_and_girls_list.html' , {'hoppy_bois_and_girls': kangas})

def roo_detail(request , roo_id):
    roo = Roo.objects.get(id=roo_id)
    r = Ride.objects.filter(roo = roo)
    rider_species = set()
    for ride in r:
        rider_species.add(ride.species.name)
    rider_species = list(rider_species)
    rest = list(Species.objects.all())
    restofthem = []
    for item in rest:
        if item.name not in rider_species:
            restofthem.append(item.name)

    print(f"rider, rest {rider_species} and {restofthem}")
    return render(request , 'roo_central/roo_deets.html', {'kanga' : roo , 'riding_form': RidingForm() , 'rider_species' : rider_species , 'restofthem':restofthem})

class RooChipped(CreateView):
    model = Roo
    fields = '__all__'

class RooUpdate(UpdateView):
    model = Roo
    fields = ['name' , 'height' , 'age' , 'description' , 'favorite_species_to_kick']

class RooDelete(DeleteView):
    model = Roo
    success_url = '/roo-list'

def ride_create(request , roo_id):
    print(f"in ride create with {request.POST}") 
    roo = Roo.objects.get(id=roo_id)
    species = Species.objects.get(id=request.POST['species'])
    new_ride = Ride(
        roo=roo,
        species=species,
        duration=request.POST['duration'],
        notes=request.POST['notes']
    )
    new_ride.save()
    return redirect('detail' , roo_id = roo_id)

def species(request):
    specs = Species.objects.all()
    return render(request, 'species/species_index.html' , {'species': specs , 'species_form':SpeciesForm()} )

def species_create(request):
    form = SpeciesForm(request.POST)
    if form.is_valid():
        form.save()
    else:
        print("Couldn't save that for some reason...")
    return redirect('species')

main_app/templates/roo_central/hoppy_bois_and_girls_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Check out all these Roo's!</h1>
{% for boi_or_girl in hoppy_bois_and_girls %}
<a href="{% url 'detail' boi_or_girl.id %}">
    <div class="card">
        <div class="card-content">
            <h1>{{boi_or_girl.name}}</h1>
            <p>Height: {{boi_or_girl.height}}</p>
            <p>Age: {{boi_or_girl.age}}</p>
            <p>Description: {{boi_or_girl.description}}</p>
            <p>Favorite Species to Kick: {{boi_or_girl.favorite_species_to_kick}}</p>
        </div>
    </div>
</a>

{% endfor %}

{% endblock %}

main_app/templates/roo_central/roo_deets.html
{% extends 'base.html' %}
{% block content %}

<div class="card">
    <div class="card-content">
        <span class="card-title">The juicy details regarding {{kanga.name}}</span>
        <p>Height (inches): {{kanga.height}}</p>
        <p>Age: {{kanga.age}}</p>
        <p>Description: {{kanga.description}}</p>
        <p>Likes to kick: {{kanga.favorite_species_to_kick}}s</p>
    </div>
    <div class="card-action">
        <a href="{% url 'roo_update' kanga.id %}">Edit</a>
        <a href="{% url 'roo_delete' kanga.id %}">Delete</a>
    </div>
</div>

<div class="card">
    <div class="card-content">
        {% for ride in kanga.ride_set.all %}
        {% if not ride %}
        <h1>Roo doesn't seem to have been ridden. Hop on them ASAP so we can document 'Homo sapien'</h1>
        {% else %}
        <div style="width:100%">
            <tr style="display:flex;flex-flow:row nowrap;justify-content:space-around; width:100%">
                <td>Duration in seconds: {{ride.duration}}</td>
                <td>By: {{ride.species}}</td>
                <td>Important Observations: {{ride.notes}} </td>
            </tr>

        </div>
        {% endif %}
        {% endfor %}

    </div>
    <div class="card-content">
        <form action="{% url 'ride_create' kanga.id %}" method="POST">
            {% csrf_token %}
            {{ riding_form.as_p }}
            <input type="submit" class="btn" value="Ride that 'Roo!">
        </form>
    </div>
</div>
<div class="card">
    <div class="card-content">
        <h1>Species that have ridden {{kanga.name}}</h1>

        {% for spec in rider_species %}
        <h2>{{spec}}</h2>
        {% endfor %}

    </div>
</div>
<div class="card">
    <div class="card-content">
        <h1>Species that have NOT ridden {{kanga.name}}</h1>
        {% for spec in restofthem %}
        <h2>{{spec}}</h2>
        {% endfor %}
    </div>
</div>

<script>
    const selectEl = document.getElementById('id_species');
    M.FormSelect.init(selectEl);
</script>
{% endblock %}